### ISSUE TITLE
Nav link for GraphQL Guide uses wrong domain

### ISSUE THREAD

**Issue by jonlachlan** [apollostack/graphql-guide#3]
Just wanted to point out, when I am on this page:

http://docs.apollostack.com/graphql/schemas.html

And I hover over the nav links for Apollo Client and Apollo Server, the URL is for apollo-stack.com, not apollostack.com. So it is the wrong URL and a dead link.

This is only a problem when I am viewing a page within the "GraphQL Guide" section of the site. The URLs are correct when I am in the other sections of the site (i.e., Apollo Client and Apollo Server).

**Comment by stubailo** [comment]
I think this website is going to disappear soon, since an updated version of graphql.org is launching with about the same information.
